#!/bin/bash
# MonoKickstart Shell Script
# Written by Ethan "flibitijibibo" Lee

# Move to script's directory
cd "`dirname "$0"`"

# Get the system architecture
UNAME=`uname`
ARCH=`uname -m`
BASENAME=`basename "$0"`

# MonoKickstart picks the right libfolder, so just execute the right binary.
if [ "$UNAME" == "Darwin" ]; then
	ext=osx
else
	if [ "$ARCH" == "x86_64" ]; then
		ext=x86_64
	else
		ext=x86
	fi
fi

./${BASENAME}.bin.${ext} $@
